version: '3.8'
services:
  mysql57:
    image: mysql:5.7
    container_name: mysqlify_test_57
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqlify_test
    ports:
      - "3307:3306"
    tmpfs:
      - /var/lib/mysql

  mysql80:
    image: mysql:8.0
    container_name: mysqlify_test_80
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqlify_test
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql

  mariadb105:
    image: mariadb:10.5
    container_name: mysqlify_test_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mysqlify_test
    ports:
      - "3309:3306"
    tmpfs:
      - /var/lib/mysql
